name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-2019, macos-latest]
        node-version: [10, 16]

    name: ${{ matrix.os }} (v${{ matrix.node-version }})
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install npm dependencies
      run: npm ci --ignore-scripts

    - name: Build artifact
      run: npm run build

    - name: Run tests
      run: npm run test
